version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      - sonarnet
    environment:
      MYSQL_DATABASE: dogood
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ROOT_HOST: localhost
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - sonarnet
    ports:
      - 8080:8080
  passbolt:
    image: passbolt/passbolt
    container_name: passbolt
    restart: always
    networks:
      - sonarnet
    environment:
#      APP_FULL_BASE_URL: https://dogood.passbolt.com
      DATASOURCES_DEFAULT_HOST: mysql
      DATASOURCES_DEFAULT_PORT: 3306
      DATASOURCES_DEFAULT_DATABASE: dogood
      DATASOURCES_DEFAULT_USERNAME: root
      DATASOURCES_DEFAULT_PASSWORD: rot
#      EMAIL_TRANSPORT_DEFAULT_CLASS_NAME:
#      EMAIL_DEFAULT_FROM:
#      EMAIL_DEFAULT_TRANSPORT:
#      EMAIL_TRANSPORT_DEFAULT_HOST:
#      EMAIL_TRANSPORT_DEFAULT_PORT:
#      EMAIL_TRANSPORT_DEFAULT_TIMEOUT:
#      EMAIL_TRANSPORT_DEFAULT_USERNAME:
#      EMAIL_TRANSPORT_DEFAULT_PASSWORD:
#      EMAIL_TRANSPORT_DEFAULT_CLIENT:
#      EMAIL_TRANSPORT_DEFAULT_TLS:
#      EMAIL_TRANSPORT_DEFAULT_URL:
#      GNUPGHOME: /home/www-data/.gnupg
#      PASSBOLT_KEY_LENGTH: 2048
#      PASSBOLT_SUBKEY_LENGTH: 2048
#      PASSBOLT_KEY_NAME:
#      PASSBOLT_KEY_EMAIL:
#      PASSBOLT_KEY_EXPIRATION:
#      PASSBOLT_GPG_SERVER_KEY_FINGERPRINT:
#      PASSBOLT_GPG_SERVER_KEY_PUBLIC: /var/www/passbolt/config/gpg/serverkey.asc
#      PASSBOLT_GPG_SERVER_KEY_PRIVATE: /var/www/passbolt/config/gpg/serverkey_private.asc
#      PASSBOLT_REGISTRATION_PUBLIC: false
#      PASSBOLT_SSL_FORCE: true
#      PASSBOLT_SECURITY_SET_HEADERS: true
#      SECURITY_SALT:
    ports:
      - 9999:80
networks:
  sonarnet:
    driver: bridge
volumes:
  mysql: