version: "2"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      - sonarnet_mysql_passbolt
    environment:
      MYSQL_DATABASE: dogood
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ROOT_HOST: '172.18.0.1'
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - sonarnet_mysql_passbolt
    ports:
      - 8080:8080
networks:
  sonarnet_mysql_passbolt:
    driver: bridge
volumes:
  mysql: