version: '2'
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: elasticsearch
    restart: always
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node
    volumes:
      - volume-elasticsearch-config:/usr/share/elasticsearch/config
    networks:
      - app_net
  cerebro:
    image: yannart/cerebro
    container_name: cerebro
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - volume-cerebro:/opt/cerebro/conf
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
volumes:
  volume-elasticsearch-config:
  volume-elasticsearch-data:
  volume-cerebro:
