version: '2'
services:
  grafana:
    image: grafana/grafana:5.0.1
    container_name: grafana
    restart: always
    ports:
      - '13000:3000'
    volumes:
      - volume-grafana:/var/lib/grafana
volumes:
  volume-grafana:
