#!/bin/bash

docker build -t jenkins-teste:latest .

docker run --privileged -d -p 4444 -e PORT=4444 jenkins-teste:latest

docker run --privileged -d -p 4444 -e PORT=4444 -p 18080:8080 dogood/jenkins:latest

docker run --privileged -d -p 4444 -e PORT=4444 -p 18080:8080 jenkins-teste:latest





#Não funciona
docker run --privileged -d -p 4444:4444 dogood/jenkins:latest
