FROM jenkins:2.60.3
MAINTAINER dogood.es <devgood@dogood.es>

USER root

RUN apt update && apt install -y docker
RUN usermod -aG docker jenkins && service docker restart

EXPOSE 8080 50000

VOLUME ["/var/jenkins_home"]

USER jenkins