---
- hostname: worker01.dogood.es
  ip: 192.168.1.1
  ram: 8192
  cpu: 8

- hostname: worker02.dogood.es
  ip: 192.168.1.2
  ram: 8192
  cpu: 8

- hostname: worker03.dogood.es
  ip: 192.168.1.3
  ram: 8192
  cpu: 8
