version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.6.8-alpine
    container_name: elasticsearch
    restart: always
    ports:
      - '9200:9200'
    volumes:
      - volume-elasticsearch-config:/usr/share/elasticsearch/config
      - volume-elasticsearch-data:/usr/share/elasticsearch/data
volumes:
  volume-elasticsearch-config:
  volume-elasticsearch-data:
