version: '2'
services:
  jenkins:
    image: '2.60.3-alpine'
    container_name: 'jenkins'
    restart: 'always'
    volumes:
      - '/opt/docker/jenkins:/var/jenkins_home'
    ports:
      - '49001:8080'
