version: '2'
services:
  jenkins:
    image: h1kkan/jenkins-docker:2.107.1
    container_name: jenkins
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - volume-jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  volume-jenkins:
