version: 2
services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    restart: always
    volumes:
      - ~/docker/jenkins:/var/jenkins_home
    ports:
      - 18080:8080
      - 50000:50000
    depends_on:
      - nexus
      - sonarqube
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus3
    restart: always
    volumes:
      - ~/docker/nexus:/nexus-data
    ports:
      - 18081:8081
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - 19000:9000
      - 19092:9092
