---
- name: installing repo for Java 8 in Ubuntu
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: install openjdk 8
  apt:
    name: oracle-java8-installer
    state: present
    update-cache: yes
    force: yes