---
# sudo apt-get
- name: call script yum.yml
  include_tasks: yum.yml

# java
- name: call script java.yml
  include_tasks: java.yml

#
- name: set authorized key for user root copying it from current user
  remote_user: root
  authorized_key:
    user: root
    state: present
    manage_dir: yes
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

# update-rc.d ntp defaults
- name: make sure ntp is started up
  service:
    name: ntp
    state: started
    enabled: yes
  ignore_errors: true

# /etc/hosts
- name: set file /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

# sudo apt-get install firewalld
- name: install firewalld
  apt:
    package: firewalld
    state: present
    update_cache: yes

# stop and disable firewalld
- name: stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: False
  ignore_errors: true

# disable selinux
- name: disable selinux
  selinux:
    state: disabled
  when: ansible_os_family|lower == "redhat" and ansible_distribution|lower != "amazon"

# set timezone
- name: set timezone
  timezone:
    name: America/Sao_Paulo

# set umask
#- name: configure umask to 0022
#  shell: umask 0022

# set umask 0022 in /etc/profile
- name: configure umask to 0027
  command: echo umask 0022 >> /etc/profile

# set ulimit
#- name: configure ulimit
#  command: ulimit -n 10000

#
#- name: configure system settings, file descriptors and number of threads
#  pam_limits:
#    domain: root
#    limit_type: "{{item.limit_type}}"
#    limit_item: "{{item.limit_item}}"
#    value: "{{item.value}}"
#  with_items:
#    - { limit_type: 'soft', limit_item: 'nofile', value: 32768 }
#    - { limit_type: 'hard', limit_item: 'nofile', value: 32768 }
#    - { limit_type: 'soft', limit_item: 'nproc', value: 32768 }
#    - { limit_type: 'hdar', limit_item: 'nproc', value: 32768 }

#
- name: reload settings from all system configuration files
  shell: sysctl --system

# nscd