# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"

hosts = YAML.load_file("hosts.yml") if File.exists?("hosts.yml")
#hosts = YAML.load_file("master/hosts.yml") if File.exists?("master/hosts.yml")

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  hosts.each do |machine|
     config.vm.define machine["hostname"] do |node|
        node.vm.network "private_network", ip: machine["ip"]
        node.vm.hostname = machine["hostname"]

        # ssh
        #node.vm.network "forwarded_port", guest: 22, host: 2222, guest_ip: machine["ip"], auto_correct: true

        # ambari ui
        #node.vm.network "forwarded_port", guest: 8080, host: 8080, guest_ip: machine["ip"], auto_correct: true

        # yarn ui
        #node.vm.network "forwarded_port", guest: 8088, host: 8088, guest_ip: machine["ip"], auto_correct: true

        # hadoop nameNode ui
        #node.vm.network "forwarded_port", guest: 50070, host: 50070, guest_ip: machine["ip"], auto_correct: true

        node.vm.provider "libvirt" do |libvirt|
           #libvirt.host = machine["hostname"]
           libvirt.memory = machine["ram"]
           libvirt.cpus = machine["cpu"]
           #libvirt.connect_via_ssh = true
           #libvirt.driver = "qemu"
           #libvirt.username = "root"
           #libvirt.host = "localhost"
           #libvirt.uri = "qemu:///system"
        end
     end
  end

  #config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "../../../ansible/playbook-master.yml"
  #   ansible.inventory_path = "../../../ansible/inventory"
  #   ansible.verbose = "vvv"
  #   ansible.host_key_checking = "false"
  #end

end
