apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-persistentvolumeclaim
  namespace: prd
  labels:
    app: elasticsearch
spec:
  securityContext:
    fsGroup: 300
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
