apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-statefulset
  namespace: prd
  labels:
    app: elasticsearch
spec:
  securityContext:
    fsGroup: 300
  serviceName: elasticsearch-service
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      securityContext:
        fsGroup: 300
      containers:
        - name: elasticsearch
          image: elasticsearch:5.6.8-alpine
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: volume-elasticsearch-config
              mountPath: /usr/share/elasticsearch/config
            - name: volume-elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: volume-elasticsearch-config
          persistentVolumeClaim:
            claimName: elasticsearch-persistentvolumeclaim
        - name: volume-elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-persistentvolumeclaim