apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: prd
  labels:
    app: elasticsearch
spec:
  securityContext:
    fsGroup: 300
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: http
  selector:
    name: elasticsearch
