apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: prd
  labels:
    app: grafana
spec:
  securityContext:
    fsGroup: 300
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
  selector:
    name: grafana