apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: grafana-statefulset
  namespace: prd
  labels:
    app: grafana
spec:
  securityContext:
    fsGroup: 300
  serviceName: grafana-service
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
    spec:
      securityContext:
        fsGroup: 300
      containers:
        - name: grafana
          image: grafana/grafana:5.0.1
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: volume-grafana
              mountPath: /var/lib/grafana
      volumes:
        - name: volume-grafana
          persistentVolumeClaim:
            claimName: grafana-persistentvolumeclaim