apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistentvolumeclaim
  namespace: prd
  labels:
    app: grafana
spec:
  securityContext:
    fsGroup: 300
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
