version: '2'
services:
  mysql:
    image: 'mysql:5.7'
    container_name: 'mysql'
    restart: 'always'
    environment:
      MYSQL_DATABASE: 'dogood'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      # MYSQL_ROOT_HOST: '172.18.0.1'
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - '~/docker/mysql:/var/lib/mysql'
    ports:
      - '13306:3306'
