version: '2'
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - rancher:/var/lib/rancher
volumes:
  rancher:
