---
# Não faço o caraleo de idéia
- name: Set authorized key for user root copying it from current user
  remote_user: root
  authorized_key:
    user: root
    state: present
    manage_dir: yes
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes

# sudo apt-get install ntp
- name: Install NTP
  apt:
    package: ntp
    state: present
    update_cache: yes

# update-rc.d ntp defaults
- name: Make sure NTP is started up
  service:
    name: ntp
    state: started
    enabled: yes

# /etc/hosts
- name: Set file /etc/hosts
  template:
    src: /templates/hosts.j2
    dest: /etc/hosts

#