---
- hostname: node01.dogood.es
  ip: 192.168.1.1
  ram: 2048
  cpu: 1

- hostname: node02.dogood.es
  ip: 192.168.1.2
  ram: 2048
  cpu: 1

- hostname: node03.dogood.es
  ip: 192.168.1.3
  ram: 2048
  cpu: 1

