---
openjdk_package: java-1.8.0-openjdk-devel
packages:
  - curl                    # curl required by Ambari
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  - ntp                     # ntp required by Hadoop
  - firewalld