version: '3.3'
services:

  kong:
    image: kong:1.0.0rc3-centos
    container_name: kong
    restart: always
    environment:
      KONG_PG_HOST: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD=: kong
    ports:
      - '8000:8000'
#      - '8001:8001' # Uncomment this line to expose admin API to the public with HTTP
      - '8443:8443'
#      - '8444:8444' # Uncomment this line to expose admin API to the public with HTTPS
    depends_on:
      - postgres
    networks:
      - kong-net
    command: kong start --run-migrations -vv

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    environment:
      PORT: 1337
      DB_ADAPTER: postgres
      DB_HOST: postgres
      DB_USER: kong
      DB_DATABASE: kong
      DB_PASSWORD: kong
    ports:
      - '1337:1337'
    depends_on:
      - kong
      - postgres
    networks:
      - kong-net

  postgres:
    image: postgres:9.6
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - '5432:5432'
    networks:
      - kong-net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge