version: '2'
services:
  kong:
    image: kong:0.12.3-alpine
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
#      POSTGRES_USER: kong-database
#      POSTGRES_DB: kong-database
#      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
    networks:
      - app_net
  konga:
    image: kong:0.12.3-alpine
    container_name: kong
    restart: always
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_DATABASE: kong-database
      NODE_ENV: development
    ports:
      - '1337:1337'
    networks:
      - app_net
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    restart: always
    environment:
#      POSTGRES_PASSWORD:
#      POSTGRES_USER:
#      PGDATA:
#      POSTGRES_DB:
#      POSTGRES_INITDB_ARGS:
#      POSTGRES_INITDB_WALDIR:
    ports:
      - '5432:5432'
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    networks:
      - app_net
  adminer:
    image: adminer:0.12.3-alpine
    container_name: adminer
    restart: always
    environment:
#      ADMINER_PLUGINS:
#      ADMINER_DESIGN:
    ports:
      - '8080:8080'
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
volumes:
  volume-postgres: