apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  containers:
    - name: jenkins
      image: jenkins:latest
      ports:
        - containerPort: 8080
        - containerPort: 50000