kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: jenkins-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: jenkins-pod
    spec:
      containers:
        - name: jenkins
          image: jenkins:2.60.3-alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: volume-jenkins
              mountPath: /var/jenkins_home
      volumes:
        - name: volume-jenkins
          persistentVolumeClaim:
            claimName: jenkins-persistentvolumeclaim
