apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jenkins-statefulset
  namespace: jenkins
  labels:
    app: jenkins
spec:
  securityContext:
    fsGroup: 300
  serviceName: jenkins-service
  replicas: 1
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      securityContext:
        fsGroup: 300
      containers:
        - name: jenkins
          image: h1kkan/jenkins-docker:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: volume-jenkins
              mountPath: /var/jenkins_home
            - name: volume-docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: volume-jenkins
          persistentVolumeClaim:
            claimName: jenkins-persistentvolumeclaim
        - name: volume-docker-socket
          hostPath:
            path: /var/run/docker.sock