apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
