apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: jenkins-deployment
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 3
  serviceName: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins:latest
          ports:
            - containerPort: 8080
            - containerPort: 50000
