apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistentvolumeclaim
  namespace: jenkins
  labels:
    app: jenkins
spec:
  securityContext:
    fsGroup: 300
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
