# -*- mode: ruby -*-
# vi: set ft=ruby :

vagrantfiles = %w[master/Vagrantfile slave/Vagrantfile]
vagrantfiles.each do |vagrantfile|
  load File.expand_path(vagrantfile) if File.exists?(vagrantfile)
end