---
- hostname: master01.dogood.es
  ip: 192.168.0.1
  ram: 3072
  cpu: 3

- hostname: management01.dogood.es
  ip: 192.168.1.1
  ram: 4096
  cpu: 4

- hostname: worker01.dogood.es
  ip: 192.168.2.1
  ram: 8192
  cpu: 8

- hostname: worker02.dogood.es
  ip: 192.168.2.2
  ram: 8192
  cpu: 8

- hostname: worker03.dogood.es
  ip: 192.168.2.3
  ram: 8192
  cpu: 8

- hostname: edge01.dogood.es
  ip: 192.168.3.1
  ram: 6144
  cpu: 6

- hostname: edge02.dogood.es
  ip: 192.168.3.2
  ram: 6144
  cpu: 6

