apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: sonar
        - name: POSTGRES_USER
          value: sonar
        image: postgres:latest
        name: postgres
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgresql
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
      restartPolicy: Always
      volumes:
      - name: postgresql
        persistentVolumeClaim:
          claimName: postgresql
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
status: {}
