apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nexus
    spec:
      containers:
      - image: sonatype/nexus3:latest
        name: nexus3
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus
      restartPolicy: Always
      volumes:
      - name: nexus
        persistentVolumeClaim:
          claimName: nexus
status: {}
