apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  ports:
  - name: "18081"
    port: 18081
    targetPort: 8081
  selector:
    io.kompose.service: nexus
status:
  loadBalancer: {}
