apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: sonarqube
  name: sonarqube
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sonarqube
    spec:
      containers:
      - env:
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://db:5432/sonar
        image: sonarqube:latest
        name: sonarqube
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /opt/sonarqube/conf
          name: sonarqube-conf
        - mountPath: /opt/sonarqube/data
          name: sonarqube-data
        - mountPath: /opt/sonarqube/extensions
          name: sonarqube-extensions
        - mountPath: /opt/sonarqube/lib/bundled-plugins
          name: sonarqube-bundled-plugins
      restartPolicy: Always
      volumes:
      - name: sonarqube-conf
        persistentVolumeClaim:
          claimName: sonarqube-conf
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-data
      - name: sonarqube-extensions
        persistentVolumeClaim:
          claimName: sonarqube-extensions
      - name: sonarqube-bundled-plugins
        persistentVolumeClaim:
          claimName: sonarqube-bundled-plugins
status: {}
