apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  labels:
    name: nexus
spec:
  securityContext:
    fsGroup: 200
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    name: nexus
