apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nexus3-statefulset
  namespace: nexus3
  labels:
    app: nexus3
spec:
  serviceName: nexus3-service
  replicas: 1
  template:
    metadata:
      labels:
       name: nexus3
    spec:
      containers:
        - name: nexus3
          image: sonatype/nexus3:3.9.0
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus3-volume
              mountPath: /nexus-data
      volumes:
        - name: nexus3-volume
          persistentVolumeClaim:
            claimName: nexus3-persistentvolumeclaim
