apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-persistentvolume
  labels:
    type: local
spec:
  storageClassName: nexus-storageclassname
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"