apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-persistentvolumeclaim
  namespace: nexus
  labels:
    app: nexus
spec:
  securityContext:
    fsGroup: 200
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi