version: "2"
services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - '8080:8080'
      - '81:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
