# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.ssh.insert_key = false

  config.vm.define "master" do |master|
     master.vm.network "private_network", ip: "192.168.0.1"

     master.vm.provider "virtualbox" do |vb|
        vb.name = "master"
        vb.memory = "1024"
        vb.cpus = 1
     end
  end

  config.vm.define "slave" do |slave|
     slave.vm.network "private_network", ip: "192.168.0.10"

     slave.vm.provider "virtualbox" do |vb|
        vb.name = "slave"
        vb.memory = "1024"
        vb.cpus = 1
     end
  end

end
