# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  config.ssh.insert_key = false

  def hostname(name, number)
    hostname = "#{name}-#{number}"
  end

  (1..2).each do |i|
     hostname = hostname("node", i)
     config.vm.define "#{hostname}" do |node|
        node.vm.network "private_network", ip: "192.168.0.#{i}", virtualbox__intnet: true
        node.vm.hostname = "#{hostname}"

        node.vm.provision "shell", inline: "echo hello from #{hostname}"

        node.vm.provider "virtualbox" do |vb|
           vb.name = "#{hostname}"
           vb.memory = "256"
           vb.cpus = 1
        end
     end
  end

end
