---
- hostname: kubemaster01.dogood.es
  ip: 192.168.3.1
  ram: 1024
  cpu: 1

- hostname: kubeworker01.dogood.es
  ip: 192.168.4.1
  ram: 1024
  cpu: 1

- hostname: kubeworker02.dogood.es
  ip: 192.168.4.2
  ram: 1024
  cpu: 1