# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"

hosts = YAML.load_file("hosts.yml") if File.exists?("hosts.yml")
hosts = YAML.load_file("master/hosts.yml") if File.exists?("master/hosts.yml")

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  hosts.each do |machine|
     config.vm.define machine["hostname"] do |node|
        node.vm.network "private_network", ip: machine["ip"]
        node.vm.hostname = machine["hostname"]

        # Ambari Home Page
        node.vm.network "forwarded_port", guest: 8080, host: 8080, guest_ip: machine["ip"]

        # YARN UI
        node.vm.network "forwarded_port", guest: 8088, host: 8088, guest_ip: machine["ip"]

        # Hadoop NameNode UI
        node.vm.network "forwarded_port", guest: 50070, host: 50070, guest_ip: machine["ip"]

        node.vm.provider "virtualbox" do |vb|
           vb.name = machine["hostname"]
           vb.memory = machine["ram"]
           vb.cpus = machine["cpu"]
        end
     end
  end

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "../ansible/playbook.yml"
     ansible.inventory_path = "../ansible/inventory"
     ansible.verbose = "vvvv"
     #ansible.host_key_checking = "false"
     ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3.5",
     }
  end

end
