version: '2'
services:
  nexus:
    image: 'sonatype/nexus3:latest'
    container_name: 'nexus3'
    restart: 'always'
    volumes:
      - '~/docker/nexus:/nexus-data'
    ports:
      - '18081:8081'
