version: '2'
services:
  nexus:
    image: 'sonatype/nexus3:3.7.1'
    container_name: 'nexus3'
    restart: 'always'
    # environment:
    #   MYSQL_DATABASE: 'c4_test'
    #   # MYSQL_ROOT_HOST: '172.18.0.1'
    #   # MYSQL_ROOT_PASSWORD: 'root'
    #   MYSQL_USER: 'root'
    #   MYSQL_PASS: 'root'
    #   # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # volumes:
    #   - '/opt/docker/mysql:/var/lib/mysql'
    # expose:
      # - '3306'
    # ports:
    #   - '3306:3306'
