version: "2"
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus3
    restart: always
    ports:
      - "18081:8081"
    volumes:
      - nexus:/nexus-data
volumes:
  nexus: