# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  config.ssh.username = "root"
  config.ssh.insert_key = false

  def hostname(name, number)
    if number < 10
        hostname = "#{name}-0#{number}"
    else
        hostname = "#{name}-#{number}"
    end
  end

  (1..2).each do |i|
     hostname = hostname("master", i)
     config.vm.define "#{hostname}" do |master|
        master.vm.network "private_network", ip: "192.168.0.#{i}", virtualbox__intnet: true
        master.vm.hostname = "#{hostname}"

        master.vm.provision "shell", inline: "echo hello from #{hostname}"

        master.vm.provider "virtualbox" do |vb|
           vb.name = "#{hostname}"
           vb.memory = "3072"
           vb.cpus = 3
        end
     end
  end

  (1..4).each do |i|
     hostname = hostname("worker", i)
     config.vm.define "#{hostname}" do |worker|
        worker.vm.network "private_network", ip: "192.168.1.#{i}"
        worker.vm.hostname = "#{hostname}"

        worker.vm.provision "shell", inline: "echo hello from #{hostname}"

        worker.vm.provider "virtualbox" do |vb|
           vb.name = "#{hostname}"
           vb.memory = "6144"
           vb.cpus = 6
        end
     end
  end

end
