
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "pocs"
  config.ssh.insert_key = false

  config.vm.define :hdp do |web_config|
    web_config.vm.network "private_network", ip: "192.168.50.10"
    web_config.vm.provision "puppet" do |puppet|
      puppet.manifest_file = "provision-script.pp"
    end
  end

  config.vm.synced_folder "manifest/", "/vagrant/manifest"

end
