version: '2'
services:
  kafka:
    image: spotify/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: 'docker-machine ip \`docker-machine active\`'
      ADVERTISED_PORT: 9092
      CONSUMER_THREADS: 1
      TOPICS: 'my-topic-1,my-topic-2'
      ZK_CONNECT: 'kafka7zookeeper:2181/root/path'
      GROUP_ID: mymirror