version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    container_name: elasticsearch
    volumes:
      - ~/docker/elasticsearch/node1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"