---
packages:
  - openssh-client          # scp required by Ambari
  - curl                    # curl required by Ambari
  - unzip                   # unzip required by Ambari
  - tar                     # tar required by Ambari
  - wget                    # wget required by Ambari
  - openssl                 # openssl required by Ambari
  - ntp                     # ntp required by Hadoop
  - python3-apt             # python-apt required by Ansible
  - libssl-dev              # openssl-devel recommended for Ranger KMS

openjdk_package: openjdk-8-jdk