apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-access-client
  namespace: api-users
  labels:
    name: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
  selector:
    name: mongodb