version: "3"
services:
  bitwarden:
    image: mprasil/bitwarden
    container_name: bitwarden
    restart: always
#    environment:
#      SIGNUPS_ALLOWED: "false"
#      INVITATIONS_ALLOWED: "false"
#      SHOW_PASSWORD_HINT: "true"
#      ROCKET_TLS: '{certs="/ssl/certs.pem",key="/ssl/key.pem"}'
#      DOMAIN: https://bitwarden.dogood.es
#      DATA_FOLDER: /persistent
#      DATABASE_URL: /database/bitwarden.sqlite3
#      ATTACHMENTS_FOLDER: /attachments
#      ICON_CACHE_FOLDER: /icon_cache
#      ROCKET_LIMITS: {json=10485760}
#      ROCKET_WORKERS: 20
#      SMTP_HOST: <smtp.domain.tld> \
#      SMTP_FROM: <bitwarden@domain.tld> \
#      SMTP_PORT: 587 \
#      SMTP_SSL: true \
#      SMTP_USERNAME: <username> \
#      SMTP_PASSWORD: <password> \
#      WEB_VAULT_ENABLED: false
#      ROCKET_PORT: 8080
    ports:
      - 8080:80
    volumes:
      - bitwarden:/data/
volumes:
  bitwarden: