---
- name: set authorized key for user root copying it from current user
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'files/id_rsa.pub') }}"
  with_items:
    - root
    - vagrant

- name: copy file /.ssh/id_rsa.pub
  copy:
    src: files/id_rsa.pub
    dest: "{{ item.path }}"
    mode: "{{ item.mod }}"
  with_items:
  - { path: '/root/.ssh/id_rsa.pub', mod: '0600' }
  - { path: '/home/vagrant/.ssh/id_rsa.pub', mod: '0606'}

- name: copy file /.ssh/id_rsa
  copy:
    src: files/id_rsa
    dest: "{{ item.path }}"
    mode: "{{ item.mod }}"
  with_items:
  - { path: '/root/.ssh/id_rsa', mod: '0600' }
  - { path: '/home/vagrant/.ssh/id_rsa', mod: '0606' }
  notify: restart sshd

- name: set file /etc/hosts
  copy:
    src: file/hosts
    dest: /etc/hosts