apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-persistentvolumeclaim
  namespace: bitwarden
  labels:
    app: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
