apiVersion: v1
kind: Service
metadata:
  name: bitwarden-service
  namespace: bitwarden
  labels:
    app: bitwarden
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  selector:
    name: bitwarden
