apiVersion: v1
kind: Service
metadata:
  name: api-images-service
  namespace: api-images
  labels:
    app: api-images
spec:
  securityContext:
    fsGroup: 501
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 8080
      name: http
  selector:
    name: api-images
