apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-access-client
  namespace: api-images
  labels:
    name: mongodb
spec:
  securityContext:
    fsGroup: 501
  type: NodePort
  ports:
    - port: 27017
  selector:
    name: mongodb