apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: api-images
  labels:
    name: mongodb
spec:
  securityContext:
    fsGroup: 501
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    name: mongodb