apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistentvolumeclaim
  namespace: api-images
  labels:
    app: mongodb
spec:
  securityContext:
    fsGroup: 501
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi