---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ packages }}"