# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.name = "jenkins"
    vb.memory = "2048"
    vb.cpus = 1
  end

  # Provisioning for jenkins master using Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioners/playbook.yml"
  end

  # config.vm.provider :aws do |aws, override|
  #     override.ssh.username = "ubuntu"
  #     override.ssh.private_key_path = "" # location of rsa private key file here
  #
  #     aws.keypair_name = ""
  #     aws.access_key_id = "" # Your access key id here
  #     aws.secret_access_key = "" # Your secret access key here
  #
  #     aws.ami = "ami-8bda99bb" # replace with AMI id generated with packer if necessary
  #     aws.security_groups = ["launch-wizard-1"] # replace with preferred security group, must have an ssh port
  #     aws.region = "us-west-2"
  #     aws.tags = {
  #       'Name' => 'jenkins',
  #       'Provisioner' => 'Medullan',
  #       'OS_Version' => 'Ubuntu',
  #       'Release' => 'Latest'
  #     }
  # end

end
