# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  config.ssh.username = "root"

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.provider "virtualbox" do |vb|
    vb.name = "jenkins"
    vb.memory = "2048"
    vb.cpus = 1
  end

  # Provisioning for jenkins master using Ansible
  # config.vm.provision "ansible" do |ansible|
  #   ansible.galaxy_role_file = "provisioners/requirements.yml"
  #   ansible.galaxy_roles_path = "/etc/ansible/roles"
  #   ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path}"
  #   ansible.playbook = "provisioners/playbook.yml"
  # end

  # config.vm.provider :aws do |aws, override|
  #     override.ssh.username = "ubuntu"
  #     override.ssh.private_key_path = "" # location of rsa private key file here
  #
  #     aws.keypair_name = ""
  #     aws.access_key_id = "" # Your access key id here
  #     aws.secret_access_key = "" # Your secret access key here
  #
  #     aws.ami = "ami-8bda99bb" # replace with AMI id generated with packer if necessary
  #     aws.security_groups = ["launch-wizard-1"] # replace with preferred security group, must have an ssh port
  #     aws.region = "us-west-2"
  #     aws.tags = {
  #       'Name' => 'jenkins',
  #       'Provisioner' => 'Medullan',
  #       'OS_Version' => 'Ubuntu',
  #       'Release' => 'Latest'
  #     }
  # end

end
